namespace Words.Models
{
    public class WordList
    {
        public List<WordEntry> wordsDone = new List<WordEntry>();
        private List<WordEntry> Words = new List<WordEntry>
{
    new WordEntry { Word = "gungstol", Category = WordCategory.Möbler },
    new WordEntry { Word = "träben", Category = WordCategory.Kroppsdel },
    new WordEntry { Word = "skratta", Category = WordCategory.Handling },
    new WordEntry { Word = "fyr", Category = WordCategory.Byggnad },
    new WordEntry { Word = "laddstolpe", Category = WordCategory.Teknik },
    new WordEntry { Word = "lurar", Category = WordCategory.Teknik },
    new WordEntry { Word = "trädgård", Category = WordCategory.Fritid },
    new WordEntry { Word = "skog", Category = WordCategory.Natur },
    new WordEntry { Word = "skogsmaskin", Category = WordCategory.Maskin },
    new WordEntry { Word = "apa", Category = WordCategory.Djur },
    new WordEntry { Word = "katt", Category = WordCategory.Djur },
    new WordEntry { Word = "hund", Category = WordCategory.Djur },
    new WordEntry { Word = "bil", Category = WordCategory.Fordon },
    new WordEntry { Word = "cykel", Category = WordCategory.Fordon },
    new WordEntry { Word = "båt", Category = WordCategory.Fordon },
    new WordEntry { Word = "hus", Category = WordCategory.Hem },
    new WordEntry { Word = "skola", Category = WordCategory.Skola },
    new WordEntry { Word = "dator", Category = WordCategory.Teknik },
    new WordEntry { Word = "telefon", Category = WordCategory.Teknik },
    new WordEntry { Word = "klocka", Category = WordCategory.Tid },
    new WordEntry { Word = "fönster", Category = WordCategory.Hem },
    new WordEntry { Word = "dörr", Category = WordCategory.Hem },
    new WordEntry { Word = "vägg", Category = WordCategory.Hem },
    new WordEntry { Word = "tak", Category = WordCategory.Hem },
    new WordEntry { Word = "golv", Category = WordCategory.Hem },
    new WordEntry { Word = "säng", Category = WordCategory.Möbler },
    new WordEntry { Word = "soffa", Category = WordCategory.Möbler },
    new WordEntry { Word = "stol", Category = WordCategory.Möbler },
    new WordEntry { Word = "bord", Category = WordCategory.Möbler },
    new WordEntry { Word = "matta", Category = WordCategory.Hem },
    new WordEntry { Word = "skåp", Category = WordCategory.Hem },
    new WordEntry { Word = "hylla", Category = WordCategory.Hem },
    new WordEntry { Word = "bokhylla", Category = WordCategory.Möbler },
    new WordEntry { Word = "tvättmaskin", Category = WordCategory.Maskin },
    new WordEntry { Word = "diskmaskin", Category = WordCategory.Maskin },
    new WordEntry { Word = "ugn", Category = WordCategory.Hem },
    new WordEntry { Word = "bok", Category = WordCategory.Kultur },
    new WordEntry { Word = "tidning", Category = WordCategory.Kommunikation },
    new WordEntry { Word = "papper", Category = WordCategory.Kommunikation },
    new WordEntry { Word = "penna", Category = WordCategory.Kommunikation },
    new WordEntry { Word = "blyertspenna", Category = WordCategory.Kommunikation },
    new WordEntry { Word = "färgpennor", Category = WordCategory.Kommunikation },
    new WordEntry { Word = "kritor", Category = WordCategory.Kommunikation },
    new WordEntry { Word = "målarfärg", Category = WordCategory.Fritid },
    new WordEntry { Word = "pensel", Category = WordCategory.Fritid },
    new WordEntry { Word = "lim", Category = WordCategory.Fritid },
    new WordEntry { Word = "klistermärke", Category = WordCategory.Fritid },
    new WordEntry { Word = "klister", Category = WordCategory.Fritid },
    new WordEntry { Word = "mat", Category = WordCategory.Mat },
    new WordEntry { Word = "dryck", Category = WordCategory.Mat },
    new WordEntry { Word = "kläder", Category = WordCategory.Kläder },
    new WordEntry { Word = "skor", Category = WordCategory.Kläder },
    new WordEntry { Word = "vantar", Category = WordCategory.Kläder },
    new WordEntry { Word = "halsduk", Category = WordCategory.Kläder },
    new WordEntry { Word = "jacka", Category = WordCategory.Kläder },
    new WordEntry { Word = "byxor", Category = WordCategory.Kläder },
    new WordEntry { Word = "skjorta", Category = WordCategory.Kläder },
    new WordEntry { Word = "klänning", Category = WordCategory.Kläder },
    new WordEntry { Word = "strumpor", Category = WordCategory.Kläder },
    new WordEntry { Word = "morgonrock", Category = WordCategory.Kläder },
    new WordEntry { Word = "pyjamas", Category = WordCategory.Kläder },
    new WordEntry { Word = "piano", Category = WordCategory.Instrument },
    new WordEntry { Word = "gitarr", Category = WordCategory.Instrument },
    new WordEntry { Word = "trummor", Category = WordCategory.Instrument },
    new WordEntry { Word = "fiol", Category = WordCategory.Instrument },
    new WordEntry { Word = "saxofon", Category = WordCategory.Instrument },
    new WordEntry { Word = "trumpet", Category = WordCategory.Instrument },
    new WordEntry { Word = "instrument", Category = WordCategory.Instrument },
    new WordEntry { Word = "musik", Category = WordCategory.Kultur },
    new WordEntry { Word = "dans", Category = WordCategory.Kultur },
    new WordEntry { Word = "teater", Category = WordCategory.Kultur },
    new WordEntry { Word = "film", Category = WordCategory.Kultur },
    new WordEntry { Word = "bokhandel", Category = WordCategory.Affär },
    new WordEntry { Word = "affär", Category = WordCategory.Affär },
    new WordEntry { Word = "restaurang", Category = WordCategory.Affär },
    new WordEntry { Word = "kafeteria", Category = WordCategory.Affär },
    new WordEntry { Word = "biograf", Category = WordCategory.Kultur },
    new WordEntry { Word = "museum", Category = WordCategory.Kultur },
    new WordEntry { Word = "park", Category = WordCategory.Natur },
    new WordEntry { Word = "strand", Category = WordCategory.Natur },
    new WordEntry { Word = "sjö", Category = WordCategory.Natur },
    new WordEntry { Word = "hav", Category = WordCategory.Natur },
    new WordEntry { Word = "fjäll", Category = WordCategory.Natur },
    new WordEntry { Word = "dal", Category = WordCategory.Natur },
    new WordEntry { Word = "härligt", Category = WordCategory.Annat },
    new WordEntry { Word = "katastrofteam", Category = WordCategory.Yrke },
    new WordEntry { Word = "fjärrtåg", Category = WordCategory.Fordon },
    new WordEntry { Word = "specialerbjudande", Category = WordCategory.Affär },
    new WordEntry { Word = "krigsveteran", Category = WordCategory.Yrke },
    new WordEntry { Word = "armborst", Category = WordCategory.Fritid },
    new WordEntry { Word = "hej", Category = WordCategory.Kommunikation },
    new WordEntry { Word = "blomkruka", Category = WordCategory.Hem },
    new WordEntry { Word = "flintskallig", Category = WordCategory.Kroppsdel },
    new WordEntry { Word = "hjärtstartare", Category = WordCategory.Teknik },
    new WordEntry { Word = "nyhetsuppläsare", Category = WordCategory.Yrke },
    new WordEntry { Word = "halvfabrikat", Category = WordCategory.Mat },
    new WordEntry { Word = "gungstol", Category = WordCategory.Möbler },
    new WordEntry { Word = "hushållspapper", Category = WordCategory.Hem },
    new WordEntry { Word = "flygel", Category = WordCategory.Instrument },
    new WordEntry { Word = "skola", Category = WordCategory.Skola },
    new WordEntry { Word = "blåsväder", Category = WordCategory.Natur },
    new WordEntry { Word = "avhandling", Category = WordCategory.Kultur },
    new WordEntry { Word = "pappersarbete", Category = WordCategory.Kommunikation },
    new WordEntry { Word = "kakburk", Category = WordCategory.Hem },
    new WordEntry { Word = "diskussion", Category = WordCategory.Kommunikation },
    new WordEntry { Word = "taxi", Category = WordCategory.Fordon },
    new WordEntry { Word = "tandvärk", Category = WordCategory.Kroppsdel },
    new WordEntry { Word = "fåntratt", Category = WordCategory.Annat },
    new WordEntry { Word = "dator", Category = WordCategory.Teknik },
    new WordEntry { Word = "hundvalp", Category = WordCategory.Djur },
    new WordEntry { Word = "polis", Category = WordCategory.Yrke },
    new WordEntry { Word = "kvalitetskontroll", Category = WordCategory.Yrke },
    new WordEntry { Word = "ord", Category = WordCategory.Kommunikation },
    new WordEntry { Word = "violin", Category = WordCategory.Instrument },
    new WordEntry { Word = "tröja", Category = WordCategory.Kläder },
    new WordEntry { Word = "hårfäste", Category = WordCategory.Kroppsdel },
    new WordEntry { Word = "balkong", Category = WordCategory.Hem },
    new WordEntry { Word = "kolonilott", Category = WordCategory.Fritid },
    new WordEntry { Word = "situation", Category = WordCategory.Annat },
    new WordEntry { Word = "blåbär", Category = WordCategory.Natur },
    new WordEntry { Word = "förbund", Category = WordCategory.Annat },
    new WordEntry { Word = "skur", Category = WordCategory.Natur },
    new WordEntry { Word = "bostad", Category = WordCategory.Hem },
    new WordEntry { Word = "demonstrant", Category = WordCategory.Yrke },
    new WordEntry { Word = "örhänge", Category = WordCategory.Fritid },
    new WordEntry { Word = "fjärrkontroll", Category = WordCategory.Teknik },
    new WordEntry { Word = "bogserlina", Category = WordCategory.Fordon },
    new WordEntry { Word = "veckodag", Category = WordCategory.Tid },
    new WordEntry { Word = "tennis", Category = WordCategory.Fritid }
};

        public List<WordEntry> GetWords()
        {
            return Words;
        }

        public WordEntry GetRandomWord()
        {
            Random random = new Random();
            int index = random.Next(Words.Count);
            return Words[index];
        }

        public List<WordEntry> GuessedWords(WordEntry word)
        {
            wordsDone.Add(word);
            return wordsDone;
        }
    }
}
